### ISSUE TITLE
Crash on FC26

### ISSUE THREAD

**Issue by vadi2** [probonopd/linuxdeployqt#198]
A user is reporting that after having upgraded from 3.5.1 to 3.6.0 ([binaries here](https://transfer.sh/)), the are getting the following crash:

```
(gdb) bt
#0  0x00000000000068b0 in  ()
#1  0x00007ffff7de6d93 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7debcea in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff4bde18f in _dl_catch_error () at /lib64/libc.so.6
#4  0x00007ffff7deb1f9 in _dl_open () at /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff4885f26 in dlopen_doit () at /lib64/libdl.so.2
#6  0x00007ffff4bde18f in _dl_catch_error () at /lib64/libc.so.6
#7  0x00007ffff48866a5 in _dlerror_run () at /lib64/libdl.so.2
#8  0x00007ffff4885fb1 in dlopen@@GLIBC_2.2.5 () at /lib64/libdl.so.2
#9  0x00007ffff36f0406 in __glXLookupVendorByName () at /lib64/libGLX.so.0
#10 0x00007ffff36f1758 in __glXLookupVendorByScreen () at /lib64/libGLX.so.0
#11 0x00007ffff36eb438 in glXChooseFBConfig () at /lib64/libGLX.so.0
#12 0x00007ffff7e61d47 in  () at /tmp/.mount_Mudlet6Ba1DQ/plugins/xcbglintegrations/libqxcb-glx-integration.so
#13 0x00007ffff7e6206d in  () at /tmp/.mount_Mudlet6Ba1DQ/plugins/xcbglintegrations/libqxcb-glx-integration.so
#14 0x00007ffff7e5e240 in  () at /tmp/.mount_Mudlet6Ba1DQ/plugins/xcbglintegrations/libqxcb-glx-integration.so
#15 0x00007fffe84a886c in QXcbWindow::create() () at /tmp/.mount_Mudlet6Ba1DQ/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#16 0x00007fffe84941f1 in QXcbIntegration::createPlatformWindow(QWindow*) const () at /tmp/.mount_Mudlet6Ba1DQ/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#17 0x00007ffff63becd2 in QWindowPrivate::create(bool, unsigned long long) () at /tmp/.mount_Mudlet6Ba1DQ/lib/libQt5Gui.so.5
#18 0x00007ffff69a9d8d in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () at /tmp/.mount_Mudlet6Ba1DQ/lib/libQt5Widgets.so.5
#19 0x00007ffff69a94c9 in QWidget::create(unsigned long long, bool, bool) () at /tmp/.mount_Mudlet6Ba1DQ/lib/libQt5Widgets.so.5
#20 0x00007ffff69b4b0a in QWidget::setVisible(bool) () at /tmp/.mount_Mudlet6Ba1DQ/lib/libQt5Widgets.so.5
#21 0x0000000000447fa0 in main ()
```

What could be going wrong?

**Comment by probonopd** [comment]
Not sure...

**Comment by TheAssassin** [comment]
@vadi2 your "binaries here" link is broken.

**Comment by vadi2** [comment]
Fixed links:
https://transfer.sh/JySVa/Mudlet-3.6.0-linux-x64.AppImage
https://transfer.sh/WRyJT/Mudlet-3.6.1-linux-x64.AppImage

**Comment by hcorion** [comment]
We've also encountered this with RPCS3's AppImages, see: https://github.com/RPCS3/rpcs3/issues/4100

AFAIK it only occurs on fedora. download is available at https://rpcs3.net/download
full backtrace:
```gdb

(gdb) bt
#0  0x00000000000068b0 in ?? ()
#1  0x00007ffff7de6d73 in _dl_init () from /lib64/ld-linux-x86-64.so.2
#2  0x00007ffff7debcca in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#3  0x00007ffff2fa99ff in _dl_catch_error () from /lib64/libc.so.6
#4  0x00007ffff7deb1d9 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#5  0x00007ffff6fbef26 in dlopen_doit () from /lib64/libdl.so.2
#6  0x00007ffff2fa99ff in _dl_catch_error () from /lib64/libc.so.6
#7  0x00007ffff6fbf6a5 in _dlerror_run () from /lib64/libdl.so.2
#8  0x00007ffff6fbefb1 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#9  0x00007ffff2c2e3b6 in __glXLookupVendorByName () from /lib64/libGLX.so.0
#10 0x00007ffff2c2f708 in __glXLookupVendorByScreen () from /lib64/libGLX.so.0
#11 0x00007ffff2c290a0 in glXQueryExtensionsString () from /lib64/libGLX.so.0
#12 0x00007fffe1fb6641 in ?? ()
   from /tmp/.mount_rpcs3-vLflKX/usr/plugins/xcbglintegrations/libqxcb-glx-integration.so
#13 0x00007fffe3d9779c in QXcbWindow::create() ()
   from /tmp/.mount_rpcs3-vLflKX/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#14 0x00007fffe3d8048e in QXcbIntegration::createPlatformWindow(QWindow*) const
    ()
   from /tmp/.mount_rpcs3-vLflKX/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#15 0x00007ffff4051896 in QWindowPrivate::create(bool, unsigned long long) ()
---Type <return> to continue, or q <return> to quit---
   from /tmp/.mount_rpcs3-vLflKX/usr/bin/../lib/libQt5Gui.so.5
#16 0x00007ffff53e5887 in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () from /tmp/.mount_rpcs3-vLflKX/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff53e5eb9 in QWidget::create(unsigned long long, bool, bool) ()
   from /tmp/.mount_rpcs3-vLflKX/usr/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff53f0919 in QWidget::setVisible(bool) ()
   from /tmp/.mount_rpcs3-vLflKX/usr/bin/../lib/libQt5Widgets.so.5
#19 0x0000000000e16eff in rpcs3_app::Init() ()
#20 0x0000000000e121bd in main ()
```
